### PR TITLE
ISSITES-5888 add article styling (badge and prismJS)

### PR DESCRIPTION
**Pull request by jotchon**
ci:test:sf

### CODE REVIEW

**Comment by jotchon** [comment]
ci:test:sf

**Comment by allen-ziegenfus** [comment]
ci:test:sf

**Comment by allen-ziegenfus** [comment]
hey @jotchon,

this is working well, but it's not formatted. in general there are a few principles to the formatting that always apply:

- always indent with tabs not spaces
- no trailing whitespace
- when in doubt and possible, sort: css properties, json key values, any lists of things

it's a little unclear how to get the source formatter to work in the workspaces folder but you can do this: 

- copy the client extensions to somewhere under `modules` and run `yarn format` from the modules directory 

that should cover some of the formatting but some of the sorting you may have to do by hand. it's better to do that while you are coding.

**Comment by allen-ziegenfus** [comment]
I've incorporated your changes here in this PR but please send a PR with the fixed formatting: https://github.com/allen-ziegenfus/liferay-portal/pull/45

Please rebase from that PR

**Pull request closed without merging**
