### PR TITLE
ISSITES-5751 SF page definitions

### PR DESCRIPTION
**Pull request by jotchon**

### CODE REVIEW

**Comment by jotchon** [comment]
I am also having issues with the info templates...  I believe the issue lies with in the `resourceClassName`.  When I look into the database, the `resourceClassName` is the same as the `className` for info templates.

**Comment by allen-ziegenfus** [comment]
@jotchon  ok let me see if i can figure it out - i thought with the ddm importer we just needed that templateentry class name - maybe i added some extra logic there

**Comment by allen-ziegenfus** [comment]
@jotchon The SVG fonts are still bothering the source formatter.  Can you please just remove the .svg font files? As far as I can tell, these are only for really old versions of iOS Safari (4.1) that are more than 8 years old.

**Comment by jotchon** [comment]
Sent a new PR for removing svg font files.  It was merged with the font commit.

**Pull request closed without merging**
