### PR TITLE
ISSITES-5840 Add Search Functionality to Public Sites Nav

### PR DESCRIPTION
**Pull request by liaoethan**

### CODE REVIEW

**Comment by allen-ziegenfus** [comment]
ci:test:sf

**Comment by allen-ziegenfus** [comment]
@liaoethan  Can you resolve the source formatting errors above? thanks

**Comment by liaoethan** [comment]
ci:test:sf

**Comment by allen-ziegenfus** [comment]
ci:test:sf

**Comment by allen-ziegenfus** [comment]
Hey @liaoethan , 

This is looking great. Here are a few things to improve:

* Add in the assetURL with a link
* Let's use the assetSearchSummary instead of content
* Sometimes there are too many results shown. I can't always recreate this but it's happening relatively often:
image
* Can you make the highlighting logic case insensitive?
* Add a Liferay.Language.get lookup for "No content preview"

**Comment by liaoethan** [comment]
ci:test:sf

**Comment by liaoethan** [comment]
ci:test:sf

**Comment by liaoethan** [comment]
Hi @allen-ziegenfus, thanks for the review. I made changes to the suggestions above. Let me know if I need to do anything additional. I squashed the commits here:
https://github.com/allen-ziegenfus/liferay-portal/pull/54

**Pull request closed without merging**
