### PR TITLE
ISSITES-5761 Public sites navigation sites button changes

### PR DESCRIPTION
**Pull request by liaoethan**

### CODE REVIEW

**Comment by allen-ziegenfus** [comment]
Hey @liaoethan 

I was trying this out on the learn master page and this was the closest I was able to get to the mockups: 

image

1. I was adding a paragraph fragment or heading fragment for the "Sites" text but it was always showing gray and also centered
2. Also when activated the "Liferay Sites" should be blue, but it's showing up as purple for me
3. When editing the master page I'm not able to easily edit the editables when I add the "Sites" text fragment into the dropdown. Am I missing something? - I thought you had tested this. I have to edit the fragment somewhere else and then drag it into the sites menu. 
4. Can you set up the learn master page so it includes the examples in the mockups so we can easily test?

**Comment by liaoethan** [comment]
Hi @allen-ziegenfus,

1. I changed the text color to black in the common styles (not exactly sure why the default color is grey) and the alignment by changing the Text Align configuration to _Justify_. However, it shouldn't default center, so I will add a change for that.
2. Looks like I had a mixup with the stylebook tokens. I'll make the changes for those as well.
3. I've been configuring it through workarounds for now. I thought we discussed that we would be testing the editables after the completion of the dropdown provider ticket: https://issues.liferay.com/browse/ISSITES-5784, maybe I misunderstood. I can add in extra js or css for now to make it easier to configure.
4. Good idea, I'll set up the learn master page and export that.

Thanks for the review and feedback! I'll make those changes ASAP.

**Comment by allen-ziegenfus** [comment]
@liaoethan  Thanks
For 1 where were you making those changes? I tried making the font color black and it showed up that way in the edit mode, but when publishing the pages were still showing gray text.
For 3 can you show me what the workarounds are? 

Allen

**Comment by liaoethan** [comment]
Hey @allen-ziegenfus,

1. I was making the changes here: 
image

It shows black for me on the pages affected
image


3. I add `display: block !important` to the liferay-sites-dropdown element.
image

Thanks,

Ethan

**Comment by allen-ziegenfus** [comment]
@liaoethan  Yes I did the same and I saw the updated color in edit mode, but when publishing it was gone.

**Comment by liaoethan** [comment]
Hi @allen-ziegenfus, I made the changes here: https://github.com/allen-ziegenfus/liferay-portal/pull/26

**Pull request closed without merging**
